### ISSUE TITLE
Cannot update code v.0.3.8

### ISSUE THREAD

**Issue by rizalfadlila** [daangn/kinesumer#9]
hi @mingrammer, my code not updated. in go.mod i already updated with tag v.0.3.8 but not changes in my code. need help

**Comment by mingrammer** [comment]
Try this instruction:

- Remove `github.com/daangn/kinesumer` from go.mod file.
- Run `rm go.sum`
- Run `go get -u github.com/daangn/kinesumer`

**Comment by rizalfadlila** [comment]
hi @mingrammer 
i already tried the instruction but not updated. please can you try update to version v.0.3.8. is it also the same there is no update?

**Comment by mingrammer** [comment]
Hm, then try it:

- Run `go clean -modcache`
- Again above process

**Comment by rizalfadlila** [comment]
still not updated. any idea @mingrammer ? 

i try go get specific branch, but at my code getting update from v3.0.7 not v.3.0.8

i think release again (retry release). what do you think?

**Comment by mingrammer** [comment]
I can't reproduce that issue. It looks like an issue of the GOPROXY cache, so you can try to set the GONOPROXY temporarily for downloading the Kinesumer. Try it please:

- Do again all the above processes except `go get ...`.
- Run `GONOPROXY="github.com/daangn" GONOSUMDB="github.com/daangn go get -u github.com/daangn/kinesumer`

**Comment by rizalfadlila** [comment]
i will try processes but i get new updated in code v0.3.8. please help me @mingrammer

**Comment by burhanudinr** [comment]
hi @mingrammer, i try to reproduce this issue, and yes the code isn't updated with tags v0.3.8

![image](https://user-images.githubusercontent.com/20137944/150715913-4bd74563-15db-4fd2-9402-39a996af795f.png)
note : line after 39 must be ClientID in v0.3.8 version

**Comment by mingrammer** [comment]
I remove the v0.3.8 tag and released v0.3.9. Please update to v0.3.9.

**Comment by rizalfadlila** [comment]
oke done. already updated. thanks very much for your support @mingrammer  :+1:

**Comment by mingrammer** [comment]
Sounds good. Thank you for raising this issue!
